-- MySQL Script generated by MySQL Workbench
-- 01/04/17 09:18:49
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`visibilitee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`visibilitee` (
  `idVisibilitee` INT(2) NOT NULL,
  `libelle` VARCHAR(45) NULL,
  PRIMARY KEY (`idVisibilitee`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`utilisateurs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`utilisateurs` (
  `idUtilisateur` INT NOT NULL,
  `nom` VARCHAR(80) NULL,
  `prenom` VARCHAR(80) NULL,
  `datenaissance` DATE NULL,
  `email` VARCHAR(80) NULL,
  `mdp` VARCHAR(40) NULL,
  PRIMARY KEY (`idUtilisateur`),
  CONSTRAINT `idVisi`
    FOREIGN KEY (`idUtilisateur`)
    REFERENCES `mydb`.`visibilitee` (`idVisibilitee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`publications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`publications` (
  `idPublication` INT NOT NULL,
  `contenu` LONGTEXT NULL,
  `date` DATETIME NULL,
  PRIMARY KEY (`idPublication`),
  UNIQUE INDEX `publicationscol_UNIQUE` (`contenu` ASC),
  CONSTRAINT `auteur`
    FOREIGN KEY (`idPublication`)
    REFERENCES `mydb`.`utilisateurs` (`idUtilisateur`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`amitiees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`amitiees` (
  `idamitiees` INT NOT NULL,
  `date` DATE NULL,
  PRIMARY KEY (`idamitiees`),
  CONSTRAINT `userA`
    FOREIGN KEY (`idamitiees`)
    REFERENCES `mydb`.`utilisateurs` (`idUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `userB`
    FOREIGN KEY (`idamitiees`)
    REFERENCES `mydb`.`utilisateurs` (`idUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`administration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`administration` (
  `id` INT NOT NULL,
  `libelle` VARCHAR(45) NULL,
  `etat` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `idUser`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`utilisateurs` (`idUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`jaime`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`jaime` (
  `idJaime` INT NOT NULL,
  PRIMARY KEY (`idJaime`),
  CONSTRAINT `idPublication`
    FOREIGN KEY (`idJaime`)
    REFERENCES `mydb`.`publications` (`idPublication`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idUtilisateur`
    FOREIGN KEY (`idJaime`)
    REFERENCES `mydb`.`utilisateurs` (`idUtilisateur`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
